features = [
"SMHoldingPercent",
"SMQuantityHold",
"SMRoi",
"SMVolume",
"SMVolumeBuy",
"TokenLiquidity",
"TokenMarketcap",
"TransactionBuyM5",
"TransactionSellM5",
"TransBuyM5ChangePercent",
"TransSellM5ChangePercent",
"VolumeM5",
"VolumeM5ChangePercent",
"TransactionBuyH1",
"TransactionSellH1",
"TransBuyH1ChangePercent",
"TransSellH1ChangePercent",
"VolumeH1",
"VolumeH1ChangePercent",
"HolderCount",
# "HolderCountChange",
"Top10HolderHolding",
"Deployed",
# "SocialMediaScore",
# "InfluencerScore",
# "NarrativeScore",
"TransactionBuyH6",
"TransactionSellH6",
"TransBuyH6ChangePercent",
"TransSellH6ChangePercent",
"VolumeH6",
"VolumeH6ChangePercent",
"TransactionBuyH24",
"TransactionSellH24",
"TransBuyH24ChangePercent",
"TransSellH24ChangePercent",
"VolumeH24",
"VolumeH24ChangePercent",
"TransactionBuy-SellM5",
"TransactionBuy-SellH1",
"TransactionBuy-SellH6",
"TransactionBuy-SellH24",
"SMAverageBuy",
]

target = "TokenPrice"

# factors = [
# "SMQuantityHold(Holder)",
# "SMVolume($)",
# "SMAverageBuy",
# "SMVolumeBuy($)",
# "TokenLiquidity($)",
# "HolderCount(Holder)",
# "VolumeM5($)",
# "VolumeH1($)",
# "VolumeH6($)",
# "TransactionBuy-SellM5",
# "TransactionBuy-SellH1",
# "TransactionBuy-SellH6",
# "Vol24h-Marketcap"
# ]

factors = [
"SMQuantityHold",
"SMVolume",
"SMAverageBuy",
"SMVolumeBuy",
"TokenLiquidity",
"HolderCount",
"VolumeM5",
"VolumeH1",
"VolumeH6",
"BS_M5",
"BS_H1",
"BS_H6",
"BS_H24",
"Vol24h-Marketcap",
"SMAverageBuy-Liquid",
"SMVolume-Liquid",
"SMVolumeBuy-Liquid",
"VolumeH1-Liquid",
"VolumeH6-Liquid",
"VolumeM5-Liquid",
"VolumeH24-Liqud"
]

range_factors= [
# "SMQuantityHold",
# "SMVolume",
# "SMAverageBuy",
# "SMVolumeBuy",
# "TokenLiquidity",
# "HolderCount",
# "VolumeM5",
# "VolumeH1",
# "VolumeH6",
# "BS_M5",
# "BS_H1",
# "BS_H6",
# "BS_H24",
# "Vol24h-Marketcap",
# "SMAverageBuy-Liquid",
# "SMVolume-Liquid",
# "SMVolumeBuy-Liquid",
"VolumeH1-Liquid",
"VolumeH6-Liquid",
"VolumeM5-Liquid",
"VolumeH24-Liqud",
]